//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSoftClean.Data.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class direcciones {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal direcciones() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppSoftClean.Data.Recursos.direcciones", typeof(direcciones).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Vistas/Formularios/FormAreaUso.aspx?id=.
        /// </summary>
        public static string FormAreaUso {
            get {
                return ResourceManager.GetString("FormAreaUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Vistas/Formularios/FormCepInBas.aspx?id=.
        /// </summary>
        public static string FormCepInBas {
            get {
                return ResourceManager.GetString("FormCepInBas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Vistas/Formularios/FormDivisiones.aspx?id=.
        /// </summary>
        public static string FormDivisiones {
            get {
                return ResourceManager.GetString("FormDivisiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Vistas/Formularios/FormDosEstLim.aspx?id=.
        /// </summary>
        public static string FormDosEstLim {
            get {
                return ResourceManager.GetString("FormDosEstLim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Vistas/Formularios/FormDosLav.aspx?id=.
        /// </summary>
        public static string FormDosLav {
            get {
                return ResourceManager.GetString("FormDosLav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Vistas/Formularios/FormHoteles.aspx?id=.
        /// </summary>
        public static string FormHoteles {
            get {
                return ResourceManager.GetString("FormHoteles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Vistas/Formularios/FormModEqDos.aspx?id=.
        /// </summary>
        public static string FormModEqDos {
            get {
                return ResourceManager.GetString("FormModEqDos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Vistas/Formularios/FormModJab.aspx?id=.
        /// </summary>
        public static string FormModJab {
            get {
                return ResourceManager.GetString("FormModJab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Vistas/Formularios/FormPorGalon.aspx?id=.
        /// </summary>
        public static string FormPortGalon {
            get {
                return ResourceManager.GetString("FormPortGalon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Vistas/Formularios/FormProdQuim.aspx?id=.
        /// </summary>
        public static string FormProdQuim {
            get {
                return ResourceManager.GetString("FormProdQuim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Vistas/Formularios/FormTipMaqLav.aspx?id=.
        /// </summary>
        public static string FormTipMaqLav {
            get {
                return ResourceManager.GetString("FormTipMaqLav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Vistas/Listas/ViewAreaUso.aspx.
        /// </summary>
        public static string ViewAreaUso {
            get {
                return ResourceManager.GetString("ViewAreaUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Vistas/Listas/ViewCepInBas.aspx.
        /// </summary>
        public static string ViewCepInBas {
            get {
                return ResourceManager.GetString("ViewCepInBas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Vistas/Listas/ViewDivisiones.aspx.
        /// </summary>
        public static string ViewDivisiones {
            get {
                return ResourceManager.GetString("ViewDivisiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Vistas/Listas/ViewDosEstLim.aspx.
        /// </summary>
        public static string ViewDosEstLim {
            get {
                return ResourceManager.GetString("ViewDosEstLim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Vistas/Listas/ViewDosLav.aspx.
        /// </summary>
        public static string ViewDosLav {
            get {
                return ResourceManager.GetString("ViewDosLav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Vistas/Listas/ViewHoteles.aspx.
        /// </summary>
        public static string ViewHoteles {
            get {
                return ResourceManager.GetString("ViewHoteles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Vistas/Listas/ViewLevantamientoEquipos.aspx?id=.
        /// </summary>
        public static string ViewLevantamientoEquipos {
            get {
                return ResourceManager.GetString("ViewLevantamientoEquipos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Vistas/Listas/ViewListaLevantamientos.aspx.
        /// </summary>
        public static string ViewListaLevantamiento {
            get {
                return ResourceManager.GetString("ViewListaLevantamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Vistas/Listas/ViewListaReportesServicio.aspx.
        /// </summary>
        public static string ViewListaReportesServicio {
            get {
                return ResourceManager.GetString("ViewListaReportesServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Vistas/Listas/ViewModEqDos.aspx.
        /// </summary>
        public static string ViewModEqDos {
            get {
                return ResourceManager.GetString("ViewModEqDos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Vistas/Listas/ViewModJab.aspx.
        /// </summary>
        public static string ViewModJab {
            get {
                return ResourceManager.GetString("ViewModJab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Vistas/Listas/ViewPorGalon.aspx.
        /// </summary>
        public static string ViewPortGalon {
            get {
                return ResourceManager.GetString("ViewPortGalon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Vistas/Listas/ViewProdQuim.aspx.
        /// </summary>
        public static string ViewProdQuim {
            get {
                return ResourceManager.GetString("ViewProdQuim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Vistas/Listas/ViewRegRepSer.aspx?id=.
        /// </summary>
        public static string ViewRegRepSer {
            get {
                return ResourceManager.GetString("ViewRegRepSer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Vistas/Listas/ViewTipMaqLav.aspx.
        /// </summary>
        public static string ViewTipMaqLav {
            get {
                return ResourceManager.GetString("ViewTipMaqLav", resourceCulture);
            }
        }
    }
}
