//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSoftClean.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Observacion
    {
        public int id { get; set; }
        public string Encontrado { get; set; }
        public string Remision { get; set; }
        public Nullable<int> idRevCom { get; set; }
    
        public virtual RevCom RevCom { get; set; }
    }
}
