//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSoftClean.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos_Area
    {
        public int id { get; set; }
        public Nullable<int> idLevantamientoEquipos { get; set; }
        public string AreaInstalacion { get; set; }
        public Nullable<int> idModEqDos { get; set; }
        public Nullable<int> idDosLim { get; set; }
        public string ProdQuim { get; set; }
        public Nullable<int> idModJab { get; set; }
        public Nullable<int> CanCepInBas { get; set; }
        public Nullable<int> idTipMaqLav { get; set; }
        public string DosLav { get; set; }
        public Nullable<int> idPorGalon { get; set; }
        public Nullable<int> CanModEqDos { get; set; }
        public Nullable<int> CanDosLim { get; set; }
        public Nullable<int> CanModJab { get; set; }
        public Nullable<int> CanTipMaqLav { get; set; }
        public Nullable<int> CanPorGalon { get; set; }
    
        public virtual AdmDosEstLim AdmDosEstLim { get; set; }
        public virtual AdmModEqDos AdmModEqDos { get; set; }
        public virtual AdmModJab AdmModJab { get; set; }
        public virtual AdmPorGalon AdmPorGalon { get; set; }
        public virtual AdmTipMaqLav AdmTipMaqLav { get; set; }
        public virtual Levantamiento_Equipos Levantamiento_Equipos { get; set; }
    }
}
