//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSoftClean.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegRepSer
    {
        public int id { get; set; }
        public string IdenArea { get; set; }
        public string idEquiDos { get; set; }
        public Nullable<int> idProdQuim { get; set; }
        public string DilucionIn { get; set; }
        public string DilucionFi { get; set; }
        public string PorGalonSi { get; set; }
        public string PorGalonNo { get; set; }
        public string Estado { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> idReporte_Servicios { get; set; }
    
        public virtual AdmProdQuim AdmProdQuim { get; set; }
        public virtual Reportes_Servicio Reportes_Servicio { get; set; }
    }
}
