//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSoftClean.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RevCom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RevCom()
        {
            this.Observacion = new HashSet<Observacion>();
        }
    
        public int id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> idCatComRev { get; set; }
        public Nullable<int> idSerLav { get; set; }
    
        public virtual CatComRev CatComRev { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Observacion> Observacion { get; set; }
        public virtual Servicios_Lavavajillas Servicios_Lavavajillas { get; set; }
    }
}
