//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSoftClean.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicios_Lavavajillas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servicios_Lavavajillas()
        {
            this.RevCom = new HashSet<RevCom>();
        }
    
        public int id { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<int> Folio { get; set; }
        public Nullable<int> idAdmTipMaqLav { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<System.DateTime> dteFecha { get; set; }
        public string DosKor { get; set; }
        public string DosAdi { get; set; }
        public string DosClo { get; set; }
        public Nullable<int> TemMinLav { get; set; }
        public Nullable<int> TemMinEnj { get; set; }
        public Nullable<int> TemAmbMax { get; set; }
        public string LimInEx { get; set; }
        public string Desincrustacion { get; set; }
        public string ProIno { get; set; }
        public Nullable<int> idServLav { get; set; }
    
        public virtual AdmTipMaqLav AdmTipMaqLav { get; set; }
        public virtual Hoteles Hoteles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RevCom> RevCom { get; set; }
    }
}
